### ISSUE TITLE
VDDP value is displayed incorrectly (seems like) in ZenTimings 1.2.1

### ISSUE THREAD

**Issue by CfYz-R** [irusanov/ZenTimings#10]
Or I wrong and this is other value inside ZenTimings, not that in my BIOS... Here the screenshots of ZT 1.2.1/HWInfo/BIOS:

ASRock motherboard, 5.50 is a latest BIOS for Ryzen 1000 series. The problem is I found that exactly this value on my RAM sticks led to stability. 0.970 have errors in MemTest5, 0.980 - nope. ZenTimings 1.2.1 shows 0.95 with 0.97 or 0.98 or other values set in BIOS.

I can provide debugs or whatever I can for you. I'm now already 5 days of trials of overclocking memory on my system, so ZenTimings are the very first tool I'm using %)

![VDDP_BIOS](https://user-images.githubusercontent.com/17078006/100608939-42578700-331e-11eb-947e-d236dad11a43.jpg)
![VDDP_HWInfo](https://user-images.githubusercontent.com/17078006/100608940-4388b400-331e-11eb-8ff8-2b864a377d18.jpg)
![VDDP_ZenTimings](https://user-images.githubusercontent.com/17078006/100608942-4388b400-331e-11eb-8d68-907538ccdc9a.jpg)

**Comment by irusanov** [comment]
CLDO VDDP and VDDP are different voltages. I don't know if the first one is exposed somewhere in your BIOS.

**Comment by CfYz-R** [comment]
> CLDO VDDP and VDDP are different voltages. I don't know if the first one is exposed somewhere in your BIOS.

Ok thanks, so I was wrong, you may close this or delete... Pictures uploaded.

BTW do you have plans to show DRAM voltage of RAM in ZT (the main voltage 1.2 spec, 1.35-1.5 for OC tuned memory kits)? And maybe VDDP too. We saving screenshots for archived purposes and in case to start OC again in furture or when new bios come out...

**Comment by irusanov** [comment]
DRAM will be included in the next release, but it will show a value only for some motherboards.
Currently it seems Asus and Asrock don't report it, but MSI does.

**Comment by CfYz-R** [comment]
Seems like that ASRock report it, at least on X370... Readings of DRAM Voltage and VTT - are correct, exact same numbers in BIOS.

![ZenTimings_10_3333_122](https://user-images.githubusercontent.com/17078006/103488811-e7cfb000-4e20-11eb-8095-50e5858bd4a3.png)

**Comment by CfYz-R** [comment]
Don't know if it's interesting, did some upgrade on my MB with BIOS and CPU and now ASRock don't report VDIMM as you said. Can do some debug if you will.
**AGESA Combo-AM4 PI 1.0.0.6**

![ZenTimings_21_3400_XMP (TM+)](https://user-images.githubusercontent.com/17078006/106655932-0ef9d880-65ab-11eb-8bae-922174dff2d9.png)
