### ISSUE TITLE
1.2.2 error 'CPU model is not supported'.

### ISSUE THREAD

**Issue by xgfancz** [irusanov/ZenTimings#12]
My cpu is amd 5600x.
![-3a8f4960c77af274](https://user-images.githubusercontent.com/76907714/103479925-e3e56300-4e0b-11eb-952e-3e101cf42e69.png)

**Comment by xgfancz** [comment]
[Debug_Report_26828001.4326753.txt](https://github.com/irusanov/ZenTimings/files/5761655/Debug_Report_26828001.4326753.txt)

**Comment by xgfancz** [comment]
1.2.2.120 version also has this error

**Comment by irusanov** [comment]
Yes, I have messed up the DLL it seems. Will try to pull the release down until I get back to my dev machine.

**Comment by irusanov** [comment]
Reuploaded, should work now.
