### ISSUE TITLE
AMD 5800x + Gigabyte B550 Auros Pro

### ISSUE THREAD

**Issue by coppersink** [irusanov/ZenTimings#15]
Using Zentimings 1.2.2  When launching it hangs on "waiting for power table" for about 15 seconds then says "I/O Driver is not responding or not loaded." 

Zen timings will launch but MCLK, FCLK, UCLK show n/a along with CLDO VDDP, CDDG CCD and VDDG IOD

**Comment by irusanov** [comment]
Hello,

Do you have some sort of an anti-cheat software installed, such as Vanguard or FACEIT?
Usually that's the reason for this problem other users are facing.

The driver gets blocked and as a result, the app can't read the power table where those values are reported.

**Comment by coppersink** [comment]
> Hello,
> 
> Do you have some sort of an anti-cheat software installed, such as Vanguard or FACEIT?
> Usually that's the reason for this problem other users are facing.
> 
> The driver gets blocked and as a result, the app can't read the power table where those values are reported.

Yes I play VALORANT occasionally and that has a resident anti-cheat tool/driver that runs.  I will try disabling it and running Zentimings again.  Thanks for your help.
