### ISSUE TITLE
ZenTimings

### ISSUE THREAD

**Issue by Engraulis** [irusanov/ZenTimings#16]
ZenTimings return gibberish instead of actual timings.
See screenshot. Same timings in BIOS, CPU-Z, RyzenTimingCheker, but different in ZenTimings
![ZenTimings1](https://user-images.githubusercontent.com/63254499/105675118-a1d6ab00-5ef9-11eb-8c34-00957d205708.png)

**Comment by irusanov** [comment]
Can you provide a debug file? Thanks.

**Comment by Engraulis** [comment]
[Debug_Report_26859775,5808319.txt](https://github.com/irusanov/ZenTimings/files/5867449/Debug_Report_26859775.5808319.txt)

**Comment by irusanov** [comment]
@Engraulis 
Thanks!
The issue is channel 1 reports different timings than channel 0 and I always read from last active channels, due to another issue on some motherboards.
If I read from first channel it will show the same as other apps in your case.

Do you have the memory on "Auto" or "XMP"?
I have AB350 board and can flash it with the same bios to test with Summit Ridge.

**Comment by irusanov** [comment]
Flashed the same bios and installed 1800X, but still can't reproduce it with 4x8GB RAM.
Both channels read the same timings. Maybe it's related to the XMP of the sticks or it's related to Windows 7.
Wonder if it's actually possible the channels to run on different primary timings.

Your Kingston sticks are rated for CAS 16, but other sticks might default to CAS 20.

Can you test different configuration? For example, switch the slots of the RAM - Hoodisk sticks in the slots of the Kingston sticks. Also maybe test with just 2x8.

I can easily change the code of the app, so it always reads first channel, but I'm curious what will change if you switch them.

**Comment by Engraulis** [comment]
I gonna lose my sanity doing RAM overclocking anymore. Today I have 0-3 errors in 30 minute RAM test, tomorrow after reboot - I get 15-50error per minute. I tried everything frequency (2133Mhz), voltages, timings, resistance with no good. 

Can you advise me - which parameter (voltage, timing, ...) can get random at different bootup, or change its significance after warming up.

Yesterday I was checking my memory using only one DIMM. Get a multiple errors at one of YONGXINSHENG DIMM. Looking carefully I notice crack in soldering of one relatively big capacitor, and 1 missing small one. I stayed up all night resoldering missing capacitor. Yesterday this YONGXINSHENG DIMM was giving me 15-50errors at first minute. Yesterday I decided to trough this RAM module to trashcan (also I was thinking of BADRAM/memmap, but it's Linux).

But today I luckily get 2-3error in 30 minute test (RAM fan disabled), and 0 errors per 30 minutes if RAM FAN enabled.... 
and after I powerdown my PC and quickly reEnable it (no cooldown - it's still warm) - I get 5-9 err per minute again :(.

NOTE: most errors are 6;0;12 - TestMem5 v0.12@1usmus_v3 testing program. 

I was thinking it was related to memVREF - but I'm not sure now. Maybe increasing memVref helps a bit but I still have unknown parameter that gets RANDOM from boot to boot. 
Maybe VTT-MEM, or CLDO_VDDP or other VDD_IO. Or maybe memory controller get crazy and set wrong timings for different memory channels?


Did you have exactly same AsRock motherboard? Or just a B350 chipset.
If you have same AsRock AB350 pro4 R2.0 - try BIOS 1.3. Starting from version 1.4 (or so) many parameter get hidden. You still can change them using Hex editor, but it needs some investigation (it has not any encryption/CRC check so it's relativly easy).

Kingston HyperX with white heatsink - Nanya memory chips. This module has XMP profile (which actually only 2666MHz, don't know about timings). Nanya is not famous - but their chips is
actually good. Get full stable 3366Mhz cl14.

YONGXINSHENG has Goodman memory chips - ThaiphoonBurner say it's Hynix. No builtin XMP profile. It's shitty ram module with bad soldering quality. Some smd capacitors get missed/or have
crack's in solder. https://aliexpress.ru/item/4001097535576.html


> Do you have the memory on "Auto" or "XMP"?
XMP off. Memory overclocking was enabled (Ram frequency set to 2666 MHz and DataBus termination was set), but all memory timings was set to Auto. It looks like ZenTimings read timing from SPD. Looking in CPU-z SPD or ThaiphoonBurner - I see many 1333Mhz preset with slightly different timings. Which one will be used by system? Also deep inside BIOS settings I have- "SPD READ optimization" parameter - read only first 256 bytes or whole 512 bytes of SPD. 

> Wonder if it's actually possible the channels to run on different primary timings.
I think it may be possible - memory controller have 2 different channels A and B.
But would DualMemory channel work with different timings?
Does nowday this DualChannel=RAID0 is strictly hardware or maybe it's some low level (BIOS) software based?

> Can you test different configuration? For example, switch the slots of the RAM - Hoodisk sticks in the slots of the Kingston sticks. Also maybe test with just 2x8.
OK i will on weekend.


Also I upload SPD dump of each module - dose it copyR protected?? :)
[RAM_SPD.zip](https://github.com/irusanov/ZenTimings/files/5876788/RAM_SPD.zip)

Also can you show memVREF, and other hidden voltages in ZenTimings.

Also at BIOS version 2.0 - ZenTimings does not show termination resistance. I like this version because it has P-states downclocking (and same memory stability as version 2.2).
![2 0bios](https://user-images.githubusercontent.com/63254499/105920894-33a0fe00-6049-11eb-8d7b-a5e0656dc6e7.png)

**Comment by irusanov** [comment]
I have B-die memory only, but mostly older revisions from 2017 and the hardest timing for me to stabilize is trcdrd.
Could not get it stable at 3600 14 flat and had to increase it to 15 for one of the kits and 16 for the other.
None of the voltages helped. At 14 I had many errors very quickly (using extreme profile from anta777), at 15 it was always around the 10 minutes mark.

Have no experience with Nanya and Hynix, but also know these new Nanya chips are actually pretty good.

I have AB350 K4 Fatality motherboard, but it accepts various bioses from all the similar B350 and B450 Asrock boards.
As for the voltages - can't add them.

**Comment by Engraulis** [comment]
> Might actually flash one of my kits with your SPD and see what happens.

How you will do that? Will you use ThaiphoonBurner for it? What if something goes wrong?

Also does AsRock has some way to flash bios if you previously flash wrong bios and now nothing works - like place USB falsh in special usb port (ASUS way), or do it from DOS inputing some commands (making *.bat file).

> If that is true, then it might be a good idea to switch the readings when a different DIMM is selected from the dropdown.

Better blink with all christmas tree colors, make some beep, and show error screen - "!Timings not identical!" :)
Or at-least show some RED text in lower right corner (you have some free space there).

> I remember VDDP voltage (not to be mistaken with CLDO_VDDP) helped me with 4x8GB B-Die sticks and 1800X 3 years ago when I was testing a similar configuration.

For now I reflashed 1.3 BIOS - and has 2 stable bootups with no error at 2666MHz and auto timings. I will try it later.

> CLDO_VDDP
This 1usmus. His DRAM memory calculator does not work at all. He just constantly speaks of CLDO_VDDP and how he is good.

DebugInfo for 1.3 BIOS
![1 3BIOS](https://user-images.githubusercontent.com/63254499/106010722-d2ba0a00-60ca-11eb-825f-a115934aa592.png)
[1.3BIOS 0err during test.txt](https://github.com/irusanov/ZenTimings/files/5881093/1.3BIOS.0err.during.test.txt)

Also: what is "SMU 25.84.0" version means?

**Comment by irusanov** [comment]
CLDO_VDDP was useful with first gen Zen and earlier bioses, it seems to be not that important now, but I only put my 1800X in the socket when testing ZenTimings.

I have a programmer and can connect it to the board and flash it with any bios.
As for the RAM, I might just create a new XMP with loose timings rather than flash yours, which is for different memory chips.

**Comment by irusanov** [comment]
Separate DCT readings added in new version. You can read them by changing selection in DIMM dropdown.
