### ISSUE TITLE
[Feature Request] Export Timmings

### ISSUE THREAD

**Issue by alexcheveau** [irusanov/ZenTimings#20]
Hi, first, thanks for your work, amazing tool!

If possible, I'd love to export all timings to a simple text file (delimited) like:

Freq;3600
tCL;16
tRP;16

**Comment by irusanov** [comment]
Hi,

I know it's not the same thing, but you can also use the debug report which exports the timings in similar format together with other things.

You can find them in the "Memory Config".
To generate a report, go to Tools -> Debug and click on Debug button. Then it can be saved as a file or you can copy the timings and save them as a new file manually.

I will think about an export functionality, but that's not a top priority at the moment.

**Comment by alexcheveau** [comment]
Amazing, it did the job thanks!
