### ISSUE TITLE
Incorrect file hash on application page

### ISSUE THREAD

**Issue by Velgus** [irusanov/ZenTimings#22]
The hash on the app page (https://zentimings.protonrom.com/) does not match the hash of the file.

On the site it list:
`344ac1d0ba0099a18c93b1ef399a399c`

It is actually:
`4300A3914FD8B7E10A6953923623D14E`

**Comment by irusanov** [comment]
Thanks, will fix it. Github does not provide the hash of the uploaded files, so I have to either:

- hardcode it on the site, but have to make sure I update it every time the release is updated
- always dowload the file and calculate the checksum, which is not an option

**Comment by irusanov** [comment]
Updated.

**Comment by Velgus** [comment]
Not so much for security as file integrity, which MD5 is sufficient for. Just noticed it because I use [Scoop](https://scoop.netlify.app/), and maintain a bucket that includes a manifest to allow installing ZenTimings. The automatic version update was failing when trying to install, due to the de-synced file integrity check

I can just have the GitHub action for the automatic updates check it manually by downloading it, but it's generally faster/preferred to use a provided hash if available.
