### ISSUE TITLE
inpoutx64 driver

### ISSUE THREAD

**Issue by gonzol** [irusanov/ZenTimings#23]
Please add this driver disabling after program close. It caused random BSODS on my system.
For long time i was thinking that was because of overclocking, but finally noticed that all minidumps have same TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE, same arguments and stack. After disabling inpoutx64.sys I have no BSODS for 2 weeks, before it was random, for example once a day, 3 days or 3 hours.
I also used Driver Verifier on inpoutx64.sys, and it immediatelly caused BSOD on ZenTimings opening. I can use ZenTimings normally, but have to disable driver after each use to avoid BSODS.

My spec:
Windows 7
AMD Ryzen 5 5600X
MSI B550 Gaming Plus
32GB 2x Crucial Ballistix BLACK 16GB(2x8) CL16 

EDIT: False positive, sorry. I got TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE today so the reason may be different.

**Comment by irusanov** [comment]
I was thinking It might be Windows 7 related as well. It would be good to get rid of that driver in some of the future releases anyway.

**Comment by makedir** [comment]
I was looking with Autoruns what drivers are installed on my Windows and found a fishy driver called "inpoutx64.sys". Took me a while to identify what tool installed it. ZenTimings... Even I never installed ZenTimings but used the portable version, it installes a permanent inpoutx64.sys driver into windows\system32... WHY!? This needs to be changed. How do I remove that driver!?
