### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by DannyDannyDan** [irusanov/ZenTimings#31]
Release file for v1.2.7 should be renamed from "ZenTimings_v1.2.7.zip" to "ZenTimings.zip" or the xml file at "https://zentimings.protonrom.com/AutoUpdater.xml" should have URL changed to "https://github.com/irusanov/ZenTimings/releases/download/v1.2.7/ZenTimings_v1.2.7.zip" so the update feature can locate the updated version.

**Comment by irusanov** [comment]
Thanks for the notice! Fixed the xml file with the correct link.

**Comment by irusanov** [comment]
Apparently, the discord link is also not fixed. I have released this version without testing on a real Zen machine as I didn't have access to my PC.
