### ISSUE TITLE
windows defender goes vrooom on the zip

### ISSUE THREAD

**Issue by monsdroid** [irusanov/ZenTimings#33]
![image](https://user-images.githubusercontent.com/1737131/208681900-37555909-16fb-4129-9d8d-94cb65cf8a7a.png)

checked with virustotal.com
![image](https://user-images.githubusercontent.com/1737131/208681532-84ce5ca7-bb5e-4364-97b5-c122b07ad64f.png)

any chance to resolve this?

**Comment by monsdroid** [comment]
btw, extracted there is no problem. probaly a checksum coincidence ont the zip?

**Comment by irusanov** [comment]
@monsdroid I have investigated yesterday, it appears to be from one single array in the code. It was fine first I uploaded it on release date, but definitions probably updated couple of days ago.

It didn't like this particular block of code (with it reworked, it is down to 2 false-positives):
https://github.com/irusanov/ZenTimings/commit/493ee05be2fd64b03ced62476232f658389f4603

There's still one more detection compared to 1.2.7 exe (2 vs 1) which I haven't found yet.

**Comment by irusanov** [comment]
1.2.7 recompiled from source: https://www.virustotal.com/gui/file/23aaea7ce1a96af5049d1f8686514a16e6892b5617bfab2b52aa1aa28da3bc3a?nocache=1

1.2.8 recompiled from source:
https://www.virustotal.com/gui/file/742490d2d9ea7f128ff379b7d9e5b89de4c56eec8c4c6b3ff6fdd528562c582d?nocache=1

1.2.8 with removed the conflicting code block
https://www.virustotal.com/gui/file/67c69c2554bafec16b5a70593701e97727c13425da43a05c70e4ec06771d4118?nocache=1

1.2.8 from master that includes the latest commit (same code block, but rewritten)
https://www.virustotal.com/gui/file/9c5721991526d06f64826dbb63210a2de797cb4824337871189dd0ee3e5af791?nocache=1

**Comment by irusanov** [comment]
New version released and it seems to be "fine" for now. There are still 2 detections on the executable and 2 on the whole zip.
One on the zip is coming from the included WinIO driver (only used for 32bit OS). Still not sure what causes the remaining 2 false-positives for ZenTimings.exe. I doubt it would be easy to workaround these, as the application needs to read memory, PCI registers, WMI, etc.
