### ISSUE TITLE
Screenshot button is hovered on screenshots itself.

### ISSUE THREAD

**Issue by CfYz-R** [irusanov/ZenTimings#8]
Cosmetical, but noiticable:)
Even on your main page on screenshot of 1.2.0 - photocamera icon is hovered, can you fix/change this?

P.S. ZT 1.2.1

**Comment by CfYz-R** [comment]
[http://scl.wsnet.ru/files/ryzen/ZenTimings_Screenshot_Button_Hover.jpg](url)
[http://scl.wsnet.ru/files/ryzen/ZenTimings_Screenshot_Normal_Window.jpg](url)

Example of what I mean.

**Comment by CfYz-R** [comment]
I think there is no need to open different issue, because it somewhat related to cosmetic too. When Ryzen DRAM calculate tRFC values from ns, after you've input them - they often reported as frfactional numbers, not whole. And thus the window of ZT 1.2.1 is getting wider by 2px - 37**8**x538 instead of 37**6**x538. I don't know if it bothers you, but just noticved this when comparing my OC results and timings play...

![ZenTimings_3466_XMP_9 (3400 TM+)](https://user-images.githubusercontent.com/17078006/101092058-18c28800-35ca-11eb-8902-8c2742fbe350.png) ||
![ZenTimings_3466_XMP_10 (3400 TM+)](https://user-images.githubusercontent.com/17078006/101092060-195b1e80-35ca-11eb-88e2-f1ba7ac994e4.png)

**Comment by irusanov** [comment]
There are 2 things I can do:
* set the same minimum width to all value fields, which will increase the overall width of the application with around 7px
* set the floating point precision of tRFC (ns) to 2 or 3, instead of 4, so the string is not longer than Enabled/Disabled.

**Comment by CfYz-R** [comment]
Maybe there is some people that using 4 digits floating point numbers for overclock tRFC, I personally doubt it but anyway. So 7px not so big trade off.

My personal opinion that 2 digits after comma - more that enough and looks clean and better overall. But all is up to you, I can only advice from user perspective:)

**Comment by irusanov** [comment]
Fixed in v1.2.2
